// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/proto/agent.proto

package server

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChatRequest represents an agent chat request
type ChatRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Query           string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	ConversationId  string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ContextEntities []string               `protobuf:"bytes,3,rep,name=context_entities,json=contextEntities,proto3" json:"context_entities,omitempty"`
	SessionId       *string                `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3,oneof" json:"session_id,omitempty"`
	// LLM provider selection
	Provider *string `protobuf:"bytes,5,opt,name=provider,proto3,oneof" json:"provider,omitempty"` // gemini, openai, groq
	Model    *string `protobuf:"bytes,6,opt,name=model,proto3,oneof" json:"model,omitempty"`       // gemini-2.0-flash, gpt-4o-mini, etc.
	// Conversation history for multi-turn context
	History       []*HistoryMessage `protobuf:"bytes,7,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ChatRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ChatRequest) GetContextEntities() []string {
	if x != nil {
		return x.ContextEntities
	}
	return nil
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *ChatRequest) GetProvider() string {
	if x != nil && x.Provider != nil {
		return *x.Provider
	}
	return ""
}

func (x *ChatRequest) GetModel() string {
	if x != nil && x.Model != nil {
		return *x.Model
	}
	return ""
}

func (x *ChatRequest) GetHistory() []*HistoryMessage {
	if x != nil {
		return x.History
	}
	return nil
}

// HistoryMessage represents a message in conversation history
type HistoryMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // user, assistant
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryMessage) Reset() {
	*x = HistoryMessage{}
	mi := &file_api_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryMessage) ProtoMessage() {}

func (x *HistoryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryMessage.ProtoReflect.Descriptor instead.
func (*HistoryMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *HistoryMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *HistoryMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// ChatResponse represents a complete agent response
type ChatResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Response        string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Reasoning       []*ReasoningStep       `protobuf:"bytes,2,rep,name=reasoning,proto3" json:"reasoning,omitempty"`
	Artifacts       []*Artifact            `protobuf:"bytes,3,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	Citations       []string               `protobuf:"bytes,4,rep,name=citations,proto3" json:"citations,omitempty"`
	ProposedActions []*ProposedAction      `protobuf:"bytes,5,rep,name=proposed_actions,json=proposedActions,proto3" json:"proposed_actions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ChatResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *ChatResponse) GetReasoning() []*ReasoningStep {
	if x != nil {
		return x.Reasoning
	}
	return nil
}

func (x *ChatResponse) GetArtifacts() []*Artifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *ChatResponse) GetCitations() []string {
	if x != nil {
		return x.Citations
	}
	return nil
}

func (x *ChatResponse) GetProposedActions() []*ProposedAction {
	if x != nil {
		return x.ProposedActions
	}
	return nil
}

// ChatChunk represents a streaming chunk
type ChatChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	Reasoning     *ReasoningStep         `protobuf:"bytes,3,opt,name=reasoning,proto3,oneof" json:"reasoning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatChunk) Reset() {
	*x = ChatChunk{}
	mi := &file_api_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatChunk) ProtoMessage() {}

func (x *ChatChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatChunk.ProtoReflect.Descriptor instead.
func (*ChatChunk) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ChatChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ChatChunk) GetReasoning() *ReasoningStep {
	if x != nil {
		return x.Reasoning
	}
	return nil
}

// ReasoningStep represents a step in the agent's reasoning
type ReasoningStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Step          int32                  `protobuf:"varint,1,opt,name=step,proto3" json:"step,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // retrieval, analysis, synthesis, action
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	DurationMs    *int64                 `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3,oneof" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReasoningStep) Reset() {
	*x = ReasoningStep{}
	mi := &file_api_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasoningStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasoningStep) ProtoMessage() {}

func (x *ReasoningStep) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReasoningStep.ProtoReflect.Descriptor instead.
func (*ReasoningStep) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ReasoningStep) GetStep() int32 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *ReasoningStep) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ReasoningStep) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ReasoningStep) GetDurationMs() int64 {
	if x != nil && x.DurationMs != nil {
		return *x.DurationMs
	}
	return 0
}

// Artifact represents a generated artifact
type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // code, diff, markdown, yaml, json
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Language      *string                `protobuf:"bytes,5,opt,name=language,proto3,oneof" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_api_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *Artifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Artifact) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Artifact) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Artifact) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Artifact) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

// ProposedAction represents an action the agent wants to take
type ProposedAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // approve, execute, confirm
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposedAction) Reset() {
	*x = ProposedAction{}
	mi := &file_api_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposedAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposedAction) ProtoMessage() {}

func (x *ProposedAction) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposedAction.ProtoReflect.Descriptor instead.
func (*ProposedAction) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ProposedAction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProposedAction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProposedAction) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProposedAction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// ActionRequest represents a UCL action request
type ActionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ActionType     string                 `protobuf:"bytes,1,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	EntityId       string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityType     string                 `protobuf:"bytes,3,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	Source         string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Payload        string                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"` // JSON string
	ConversationId *string                `protobuf:"bytes,6,opt,name=conversation_id,json=conversationId,proto3,oneof" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActionRequest) Reset() {
	*x = ActionRequest{}
	mi := &file_api_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRequest) ProtoMessage() {}

func (x *ActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRequest.ProtoReflect.Descriptor instead.
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ActionRequest) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *ActionRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *ActionRequest) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *ActionRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ActionRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *ActionRequest) GetConversationId() string {
	if x != nil && x.ConversationId != nil {
		return *x.ConversationId
	}
	return ""
}

// ActionResponse represents a UCL action response
type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ActionType    string                 `protobuf:"bytes,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	EntityId      string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *string                `protobuf:"bytes,5,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"`
	PreviousState *string                `protobuf:"bytes,6,opt,name=previous_state,json=previousState,proto3,oneof" json:"previous_state,omitempty"` // JSON string
	NewState      *string                `protobuf:"bytes,7,opt,name=new_state,json=newState,proto3,oneof" json:"new_state,omitempty"`                // JSON string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_api_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResponse) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *ActionResponse) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *ActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ActionResponse) GetTimestamp() string {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return ""
}

func (x *ActionResponse) GetPreviousState() string {
	if x != nil && x.PreviousState != nil {
		return *x.PreviousState
	}
	return ""
}

func (x *ActionResponse) GetNewState() string {
	if x != nil && x.NewState != nil {
		return *x.NewState
	}
	return ""
}

var File_api_proto_agent_proto protoreflect.FileDescriptor

const file_api_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/agent.proto\x12\x05agent\"\xae\x02\n" +
	"\vChatRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12)\n" +
	"\x10context_entities\x18\x03 \x03(\tR\x0fcontextEntities\x12\"\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tH\x00R\tsessionId\x88\x01\x01\x12\x1f\n" +
	"\bprovider\x18\x05 \x01(\tH\x01R\bprovider\x88\x01\x01\x12\x19\n" +
	"\x05model\x18\x06 \x01(\tH\x02R\x05model\x88\x01\x01\x12/\n" +
	"\ahistory\x18\a \x03(\v2\x15.agent.HistoryMessageR\ahistoryB\r\n" +
	"\v_session_idB\v\n" +
	"\t_providerB\b\n" +
	"\x06_model\">\n" +
	"\x0eHistoryMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xed\x01\n" +
	"\fChatResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse\x122\n" +
	"\treasoning\x18\x02 \x03(\v2\x14.agent.ReasoningStepR\treasoning\x12-\n" +
	"\tartifacts\x18\x03 \x03(\v2\x0f.agent.ArtifactR\tartifacts\x12\x1c\n" +
	"\tcitations\x18\x04 \x03(\tR\tcitations\x12@\n" +
	"\x10proposed_actions\x18\x05 \x03(\v2\x15.agent.ProposedActionR\x0fproposedActions\"\x80\x01\n" +
	"\tChatChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x127\n" +
	"\treasoning\x18\x03 \x01(\v2\x14.agent.ReasoningStepH\x00R\treasoning\x88\x01\x01B\f\n" +
	"\n" +
	"_reasoning\"\x87\x01\n" +
	"\rReasoningStep\x12\x12\n" +
	"\x04step\x18\x01 \x01(\x05R\x04step\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12$\n" +
	"\vduration_ms\x18\x04 \x01(\x03H\x00R\n" +
	"durationMs\x88\x01\x01B\x0e\n" +
	"\f_duration_ms\"\x8c\x01\n" +
	"\bArtifact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1f\n" +
	"\blanguage\x18\x05 \x01(\tH\x00R\blanguage\x88\x01\x01B\v\n" +
	"\t_language\"l\n" +
	"\x0eProposedAction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\xe2\x01\n" +
	"\rActionRequest\x12\x1f\n" +
	"\vaction_type\x18\x01 \x01(\tR\n" +
	"actionType\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x1f\n" +
	"\ventity_type\x18\x03 \x01(\tR\n" +
	"entityType\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x18\n" +
	"\apayload\x18\x05 \x01(\tR\apayload\x12,\n" +
	"\x0fconversation_id\x18\x06 \x01(\tH\x00R\x0econversationId\x88\x01\x01B\x12\n" +
	"\x10_conversation_id\"\xa2\x02\n" +
	"\x0eActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vaction_type\x18\x02 \x01(\tR\n" +
	"actionType\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12!\n" +
	"\ttimestamp\x18\x05 \x01(\tH\x00R\ttimestamp\x88\x01\x01\x12*\n" +
	"\x0eprevious_state\x18\x06 \x01(\tH\x01R\rpreviousState\x88\x01\x01\x12 \n" +
	"\tnew_state\x18\a \x01(\tH\x02R\bnewState\x88\x01\x01B\f\n" +
	"\n" +
	"_timestampB\x11\n" +
	"\x0f_previous_stateB\f\n" +
	"\n" +
	"_new_state2\xb3\x01\n" +
	"\fAgentService\x12/\n" +
	"\x04Chat\x12\x12.agent.ChatRequest\x1a\x13.agent.ChatResponse\x124\n" +
	"\n" +
	"StreamChat\x12\x12.agent.ChatRequest\x1a\x10.agent.ChatChunk0\x01\x12<\n" +
	"\rExecuteAction\x12\x14.agent.ActionRequest\x1a\x15.agent.ActionResponseB9Z7github.com/antigravity/go-agent-service/internal/serverb\x06proto3"

var (
	file_api_proto_agent_proto_rawDescOnce sync.Once
	file_api_proto_agent_proto_rawDescData []byte
)

func file_api_proto_agent_proto_rawDescGZIP() []byte {
	file_api_proto_agent_proto_rawDescOnce.Do(func() {
		file_api_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_agent_proto_rawDesc), len(file_api_proto_agent_proto_rawDesc)))
	})
	return file_api_proto_agent_proto_rawDescData
}

var file_api_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_agent_proto_goTypes = []any{
	(*ChatRequest)(nil),    // 0: agent.ChatRequest
	(*HistoryMessage)(nil), // 1: agent.HistoryMessage
	(*ChatResponse)(nil),   // 2: agent.ChatResponse
	(*ChatChunk)(nil),      // 3: agent.ChatChunk
	(*ReasoningStep)(nil),  // 4: agent.ReasoningStep
	(*Artifact)(nil),       // 5: agent.Artifact
	(*ProposedAction)(nil), // 6: agent.ProposedAction
	(*ActionRequest)(nil),  // 7: agent.ActionRequest
	(*ActionResponse)(nil), // 8: agent.ActionResponse
}
var file_api_proto_agent_proto_depIdxs = []int32{
	1, // 0: agent.ChatRequest.history:type_name -> agent.HistoryMessage
	4, // 1: agent.ChatResponse.reasoning:type_name -> agent.ReasoningStep
	5, // 2: agent.ChatResponse.artifacts:type_name -> agent.Artifact
	6, // 3: agent.ChatResponse.proposed_actions:type_name -> agent.ProposedAction
	4, // 4: agent.ChatChunk.reasoning:type_name -> agent.ReasoningStep
	0, // 5: agent.AgentService.Chat:input_type -> agent.ChatRequest
	0, // 6: agent.AgentService.StreamChat:input_type -> agent.ChatRequest
	7, // 7: agent.AgentService.ExecuteAction:input_type -> agent.ActionRequest
	2, // 8: agent.AgentService.Chat:output_type -> agent.ChatResponse
	3, // 9: agent.AgentService.StreamChat:output_type -> agent.ChatChunk
	8, // 10: agent.AgentService.ExecuteAction:output_type -> agent.ActionResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_agent_proto_init() }
func file_api_proto_agent_proto_init() {
	if File_api_proto_agent_proto != nil {
		return
	}
	file_api_proto_agent_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_proto_agent_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_proto_agent_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_proto_agent_proto_msgTypes[5].OneofWrappers = []any{}
	file_api_proto_agent_proto_msgTypes[7].OneofWrappers = []any{}
	file_api_proto_agent_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_agent_proto_rawDesc), len(file_api_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_agent_proto_goTypes,
		DependencyIndexes: file_api_proto_agent_proto_depIdxs,
		MessageInfos:      file_api_proto_agent_proto_msgTypes,
	}.Build()
	File_api_proto_agent_proto = out.File
	file_api_proto_agent_proto_goTypes = nil
	file_api_proto_agent_proto_depIdxs = nil
}
