FROM golang:1.24-alpine as builder

WORKDIR /app

RUN apk add --no-cache protobuf-dev make

COPY go.mod go.sum* ./
RUN go mod download || true

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /keystore ./cmd/keystore

FROM alpine:3.19

WORKDIR /app

COPY --from=builder /keystore /app/keystore

EXPOSE 9200

CMD ["/app/keystore"]
