// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: ucl.proto

package uclpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UCLService_ListEndpointTemplates_FullMethodName     = "/ucl.v1.UCLService/ListEndpointTemplates"
	UCLService_BuildEndpointConfig_FullMethodName       = "/ucl.v1.UCLService/BuildEndpointConfig"
	UCLService_TestEndpointConnection_FullMethodName    = "/ucl.v1.UCLService/TestEndpointConnection"
	UCLService_ValidateConfig_FullMethodName            = "/ucl.v1.UCLService/ValidateConfig"
	UCLService_ListDatasets_FullMethodName              = "/ucl.v1.UCLService/ListDatasets"
	UCLService_GetSchema_FullMethodName                 = "/ucl.v1.UCLService/GetSchema"
	UCLService_ProbeEndpointCapabilities_FullMethodName = "/ucl.v1.UCLService/ProbeEndpointCapabilities"
	UCLService_StartOperation_FullMethodName            = "/ucl.v1.UCLService/StartOperation"
	UCLService_GetOperation_FullMethodName              = "/ucl.v1.UCLService/GetOperation"
	UCLService_GetRunSummary_FullMethodName             = "/ucl.v1.UCLService/GetRunSummary"
	UCLService_DiffRunSummaries_FullMethodName          = "/ucl.v1.UCLService/DiffRunSummaries"
)

// UCLServiceClient is the client API for UCLService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UCLService provides the Universal Connectivity Layer API.
// This replaces the Python CLI (endpoint_registry_cli.py) with gRPC.
type UCLServiceClient interface {
	// ListEndpointTemplates returns available endpoint templates.
	ListEndpointTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error)
	// BuildEndpointConfig creates an endpoint configuration from a template.
	BuildEndpointConfig(ctx context.Context, in *BuildConfigRequest, opts ...grpc.CallOption) (*BuildConfigResponse, error)
	// TestEndpointConnection tests connectivity to an endpoint.
	TestEndpointConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*TestConnectionResponse, error)
	// ValidateConfig validates an endpoint configuration.
	ValidateConfig(ctx context.Context, in *ValidateConfigRequest, opts ...grpc.CallOption) (*ValidateConfigResponse, error)
	// ListDatasets returns available datasets for an endpoint.
	ListDatasets(ctx context.Context, in *ListDatasetsRequest, opts ...grpc.CallOption) (*ListDatasetsResponse, error)
	// GetSchema returns the schema for a dataset.
	GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error)
	// ProbeEndpointCapabilities performs a capability handshake.
	ProbeEndpointCapabilities(ctx context.Context, in *ProbeCapabilitiesRequest, opts ...grpc.CallOption) (*ProbeCapabilitiesResponse, error)
	// StartOperation starts a long-running connector workflow.
	StartOperation(ctx context.Context, in *StartOperationRequest, opts ...grpc.CallOption) (*StartOperationResponse, error)
	// GetOperation polls long-running workflow state.
	GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*OperationState, error)
	// GetRunSummary returns clustering/indexing summary for an artifact/run.
	GetRunSummary(ctx context.Context, in *RunSummaryRequest, opts ...grpc.CallOption) (*RunSummaryResponse, error)
	// DiffRunSummaries compares two artifacts by version hash and returns log paths for replay.
	DiffRunSummaries(ctx context.Context, in *DiffRunSummariesRequest, opts ...grpc.CallOption) (*DiffRunSummariesResponse, error)
}

type uCLServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUCLServiceClient(cc grpc.ClientConnInterface) UCLServiceClient {
	return &uCLServiceClient{cc}
}

func (c *uCLServiceClient) ListEndpointTemplates(ctx context.Context, in *ListTemplatesRequest, opts ...grpc.CallOption) (*ListTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTemplatesResponse)
	err := c.cc.Invoke(ctx, UCLService_ListEndpointTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uCLServiceClient) BuildEndpointConfig(ctx context.Context, in *BuildConfigRequest, opts ...grpc.CallOption) (*BuildConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildConfigResponse)
	err := c.cc.Invoke(ctx, UCLService_BuildEndpointConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uCLServiceClient) TestEndpointConnection(ctx context.Context, in *TestConnectionRequest, opts ...grpc.CallOption) (*TestConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestConnectionResponse)
	err := c.cc.Invoke(ctx, UCLService_TestEndpointConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uCLServiceClient) ValidateConfig(ctx context.Context, in *ValidateConfigRequest, opts ...grpc.CallOption) (*ValidateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateConfigResponse)
	err := c.cc.Invoke(ctx, UCLService_ValidateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uCLServiceClient) ListDatasets(ctx context.Context, in *ListDatasetsRequest, opts ...grpc.CallOption) (*ListDatasetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDatasetsResponse)
	err := c.cc.Invoke(ctx, UCLService_ListDatasets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uCLServiceClient) GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSchemaResponse)
	err := c.cc.Invoke(ctx, UCLService_GetSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uCLServiceClient) ProbeEndpointCapabilities(ctx context.Context, in *ProbeCapabilitiesRequest, opts ...grpc.CallOption) (*ProbeCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProbeCapabilitiesResponse)
	err := c.cc.Invoke(ctx, UCLService_ProbeEndpointCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uCLServiceClient) StartOperation(ctx context.Context, in *StartOperationRequest, opts ...grpc.CallOption) (*StartOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartOperationResponse)
	err := c.cc.Invoke(ctx, UCLService_StartOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uCLServiceClient) GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*OperationState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationState)
	err := c.cc.Invoke(ctx, UCLService_GetOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uCLServiceClient) GetRunSummary(ctx context.Context, in *RunSummaryRequest, opts ...grpc.CallOption) (*RunSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunSummaryResponse)
	err := c.cc.Invoke(ctx, UCLService_GetRunSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uCLServiceClient) DiffRunSummaries(ctx context.Context, in *DiffRunSummariesRequest, opts ...grpc.CallOption) (*DiffRunSummariesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiffRunSummariesResponse)
	err := c.cc.Invoke(ctx, UCLService_DiffRunSummaries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UCLServiceServer is the server API for UCLService service.
// All implementations must embed UnimplementedUCLServiceServer
// for forward compatibility.
//
// UCLService provides the Universal Connectivity Layer API.
// This replaces the Python CLI (endpoint_registry_cli.py) with gRPC.
type UCLServiceServer interface {
	// ListEndpointTemplates returns available endpoint templates.
	ListEndpointTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error)
	// BuildEndpointConfig creates an endpoint configuration from a template.
	BuildEndpointConfig(context.Context, *BuildConfigRequest) (*BuildConfigResponse, error)
	// TestEndpointConnection tests connectivity to an endpoint.
	TestEndpointConnection(context.Context, *TestConnectionRequest) (*TestConnectionResponse, error)
	// ValidateConfig validates an endpoint configuration.
	ValidateConfig(context.Context, *ValidateConfigRequest) (*ValidateConfigResponse, error)
	// ListDatasets returns available datasets for an endpoint.
	ListDatasets(context.Context, *ListDatasetsRequest) (*ListDatasetsResponse, error)
	// GetSchema returns the schema for a dataset.
	GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error)
	// ProbeEndpointCapabilities performs a capability handshake.
	ProbeEndpointCapabilities(context.Context, *ProbeCapabilitiesRequest) (*ProbeCapabilitiesResponse, error)
	// StartOperation starts a long-running connector workflow.
	StartOperation(context.Context, *StartOperationRequest) (*StartOperationResponse, error)
	// GetOperation polls long-running workflow state.
	GetOperation(context.Context, *GetOperationRequest) (*OperationState, error)
	// GetRunSummary returns clustering/indexing summary for an artifact/run.
	GetRunSummary(context.Context, *RunSummaryRequest) (*RunSummaryResponse, error)
	// DiffRunSummaries compares two artifacts by version hash and returns log paths for replay.
	DiffRunSummaries(context.Context, *DiffRunSummariesRequest) (*DiffRunSummariesResponse, error)
	mustEmbedUnimplementedUCLServiceServer()
}

// UnimplementedUCLServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUCLServiceServer struct{}

func (UnimplementedUCLServiceServer) ListEndpointTemplates(context.Context, *ListTemplatesRequest) (*ListTemplatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEndpointTemplates not implemented")
}
func (UnimplementedUCLServiceServer) BuildEndpointConfig(context.Context, *BuildConfigRequest) (*BuildConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildEndpointConfig not implemented")
}
func (UnimplementedUCLServiceServer) TestEndpointConnection(context.Context, *TestConnectionRequest) (*TestConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestEndpointConnection not implemented")
}
func (UnimplementedUCLServiceServer) ValidateConfig(context.Context, *ValidateConfigRequest) (*ValidateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateConfig not implemented")
}
func (UnimplementedUCLServiceServer) ListDatasets(context.Context, *ListDatasetsRequest) (*ListDatasetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDatasets not implemented")
}
func (UnimplementedUCLServiceServer) GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedUCLServiceServer) ProbeEndpointCapabilities(context.Context, *ProbeCapabilitiesRequest) (*ProbeCapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProbeEndpointCapabilities not implemented")
}
func (UnimplementedUCLServiceServer) StartOperation(context.Context, *StartOperationRequest) (*StartOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartOperation not implemented")
}
func (UnimplementedUCLServiceServer) GetOperation(context.Context, *GetOperationRequest) (*OperationState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOperation not implemented")
}
func (UnimplementedUCLServiceServer) GetRunSummary(context.Context, *RunSummaryRequest) (*RunSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRunSummary not implemented")
}
func (UnimplementedUCLServiceServer) DiffRunSummaries(context.Context, *DiffRunSummariesRequest) (*DiffRunSummariesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiffRunSummaries not implemented")
}
func (UnimplementedUCLServiceServer) mustEmbedUnimplementedUCLServiceServer() {}
func (UnimplementedUCLServiceServer) testEmbeddedByValue()                    {}

// UnsafeUCLServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UCLServiceServer will
// result in compilation errors.
type UnsafeUCLServiceServer interface {
	mustEmbedUnimplementedUCLServiceServer()
}

func RegisterUCLServiceServer(s grpc.ServiceRegistrar, srv UCLServiceServer) {
	// If the following call panics, it indicates UnimplementedUCLServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UCLService_ServiceDesc, srv)
}

func _UCLService_ListEndpointTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UCLServiceServer).ListEndpointTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UCLService_ListEndpointTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UCLServiceServer).ListEndpointTemplates(ctx, req.(*ListTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UCLService_BuildEndpointConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UCLServiceServer).BuildEndpointConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UCLService_BuildEndpointConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UCLServiceServer).BuildEndpointConfig(ctx, req.(*BuildConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UCLService_TestEndpointConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UCLServiceServer).TestEndpointConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UCLService_TestEndpointConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UCLServiceServer).TestEndpointConnection(ctx, req.(*TestConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UCLService_ValidateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UCLServiceServer).ValidateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UCLService_ValidateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UCLServiceServer).ValidateConfig(ctx, req.(*ValidateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UCLService_ListDatasets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDatasetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UCLServiceServer).ListDatasets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UCLService_ListDatasets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UCLServiceServer).ListDatasets(ctx, req.(*ListDatasetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UCLService_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UCLServiceServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UCLService_GetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UCLServiceServer).GetSchema(ctx, req.(*GetSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UCLService_ProbeEndpointCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProbeCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UCLServiceServer).ProbeEndpointCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UCLService_ProbeEndpointCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UCLServiceServer).ProbeEndpointCapabilities(ctx, req.(*ProbeCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UCLService_StartOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UCLServiceServer).StartOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UCLService_StartOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UCLServiceServer).StartOperation(ctx, req.(*StartOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UCLService_GetOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UCLServiceServer).GetOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UCLService_GetOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UCLServiceServer).GetOperation(ctx, req.(*GetOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UCLService_GetRunSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UCLServiceServer).GetRunSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UCLService_GetRunSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UCLServiceServer).GetRunSummary(ctx, req.(*RunSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UCLService_DiffRunSummaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiffRunSummariesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UCLServiceServer).DiffRunSummaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UCLService_DiffRunSummaries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UCLServiceServer).DiffRunSummaries(ctx, req.(*DiffRunSummariesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UCLService_ServiceDesc is the grpc.ServiceDesc for UCLService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UCLService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ucl.v1.UCLService",
	HandlerType: (*UCLServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListEndpointTemplates",
			Handler:    _UCLService_ListEndpointTemplates_Handler,
		},
		{
			MethodName: "BuildEndpointConfig",
			Handler:    _UCLService_BuildEndpointConfig_Handler,
		},
		{
			MethodName: "TestEndpointConnection",
			Handler:    _UCLService_TestEndpointConnection_Handler,
		},
		{
			MethodName: "ValidateConfig",
			Handler:    _UCLService_ValidateConfig_Handler,
		},
		{
			MethodName: "ListDatasets",
			Handler:    _UCLService_ListDatasets_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _UCLService_GetSchema_Handler,
		},
		{
			MethodName: "ProbeEndpointCapabilities",
			Handler:    _UCLService_ProbeEndpointCapabilities_Handler,
		},
		{
			MethodName: "StartOperation",
			Handler:    _UCLService_StartOperation_Handler,
		},
		{
			MethodName: "GetOperation",
			Handler:    _UCLService_GetOperation_Handler,
		},
		{
			MethodName: "GetRunSummary",
			Handler:    _UCLService_GetRunSummary_Handler,
		},
		{
			MethodName: "DiffRunSummaries",
			Handler:    _UCLService_DiffRunSummaries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ucl.proto",
}
