// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: gateway.proto

package gatewaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionMode int32

const (
	ExecutionMode_EXECUTION_MODE_UNSPECIFIED ExecutionMode = 0
	ExecutionMode_EXECUTION_MODE_SYNC        ExecutionMode = 1
	ExecutionMode_EXECUTION_MODE_ASYNC       ExecutionMode = 2
)

// Enum value maps for ExecutionMode.
var (
	ExecutionMode_name = map[int32]string{
		0: "EXECUTION_MODE_UNSPECIFIED",
		1: "EXECUTION_MODE_SYNC",
		2: "EXECUTION_MODE_ASYNC",
	}
	ExecutionMode_value = map[string]int32{
		"EXECUTION_MODE_UNSPECIFIED": 0,
		"EXECUTION_MODE_SYNC":        1,
		"EXECUTION_MODE_ASYNC":       2,
	}
)

func (x ExecutionMode) Enum() *ExecutionMode {
	p := new(ExecutionMode)
	*p = x
	return p
}

func (x ExecutionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_proto_enumTypes[0].Descriptor()
}

func (ExecutionMode) Type() protoreflect.EnumType {
	return &file_gateway_proto_enumTypes[0]
}

func (x ExecutionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionMode.Descriptor instead.
func (ExecutionMode) EnumDescriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0}
}

type ListEndpointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Environment   string                 `protobuf:"bytes,1,opt,name=environment,proto3" json:"environment,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEndpointsRequest) Reset() {
	*x = ListEndpointsRequest{}
	mi := &file_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEndpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndpointsRequest) ProtoMessage() {}

func (x *ListEndpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndpointsRequest.ProtoReflect.Descriptor instead.
func (*ListEndpointsRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *ListEndpointsRequest) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *ListEndpointsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type EndpointDescription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TemplateId    string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointDescription) Reset() {
	*x = EndpointDescription{}
	mi := &file_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointDescription) ProtoMessage() {}

func (x *EndpointDescription) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointDescription.ProtoReflect.Descriptor instead.
func (*EndpointDescription) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *EndpointDescription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EndpointDescription) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *EndpointDescription) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type ListEndpointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []*EndpointDescription `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEndpointsResponse) Reset() {
	*x = ListEndpointsResponse{}
	mi := &file_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEndpointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEndpointsResponse) ProtoMessage() {}

func (x *ListEndpointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEndpointsResponse.ProtoReflect.Descriptor instead.
func (*ListEndpointsResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *ListEndpointsResponse) GetEndpoints() []*EndpointDescription {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type GetEndpointDescriptorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEndpointDescriptorRequest) Reset() {
	*x = GetEndpointDescriptorRequest{}
	mi := &file_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEndpointDescriptorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEndpointDescriptorRequest) ProtoMessage() {}

func (x *GetEndpointDescriptorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEndpointDescriptorRequest.ProtoReflect.Descriptor instead.
func (*GetEndpointDescriptorRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *GetEndpointDescriptorRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

type GetEndpointDescriptorResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Family        string                  `protobuf:"bytes,2,opt,name=family,proto3" json:"family,omitempty"`
	Title         string                  `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Vendor        string                  `protobuf:"bytes,4,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Description   string                  `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Categories    []string                `protobuf:"bytes,6,rep,name=categories,proto3" json:"categories,omitempty"`
	Fields        []*FieldDescriptor      `protobuf:"bytes,7,rep,name=fields,proto3" json:"fields,omitempty"`
	Capabilities  []*CapabilityDescriptor `protobuf:"bytes,8,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEndpointDescriptorResponse) Reset() {
	*x = GetEndpointDescriptorResponse{}
	mi := &file_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEndpointDescriptorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEndpointDescriptorResponse) ProtoMessage() {}

func (x *GetEndpointDescriptorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEndpointDescriptorResponse.ProtoReflect.Descriptor instead.
func (*GetEndpointDescriptorResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *GetEndpointDescriptorResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetEndpointDescriptorResponse) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *GetEndpointDescriptorResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetEndpointDescriptorResponse) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *GetEndpointDescriptorResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GetEndpointDescriptorResponse) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *GetEndpointDescriptorResponse) GetFields() []*FieldDescriptor {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *GetEndpointDescriptorResponse) GetCapabilities() []*CapabilityDescriptor {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type FieldDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	ValueType     string                 `protobuf:"bytes,3,opt,name=value_type,json=valueType,proto3" json:"value_type,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	Semantic      string                 `protobuf:"bytes,5,opt,name=semantic,proto3" json:"semantic,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Placeholder   string                 `protobuf:"bytes,7,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,8,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Advanced      bool                   `protobuf:"varint,9,opt,name=advanced,proto3" json:"advanced,omitempty"`
	Sensitive     bool                   `protobuf:"varint,10,opt,name=sensitive,proto3" json:"sensitive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldDescriptor) Reset() {
	*x = FieldDescriptor{}
	mi := &file_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldDescriptor) ProtoMessage() {}

func (x *FieldDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldDescriptor.ProtoReflect.Descriptor instead.
func (*FieldDescriptor) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *FieldDescriptor) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FieldDescriptor) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *FieldDescriptor) GetValueType() string {
	if x != nil {
		return x.ValueType
	}
	return ""
}

func (x *FieldDescriptor) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *FieldDescriptor) GetSemantic() string {
	if x != nil {
		return x.Semantic
	}
	return ""
}

func (x *FieldDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FieldDescriptor) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *FieldDescriptor) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *FieldDescriptor) GetAdvanced() bool {
	if x != nil {
		return x.Advanced
	}
	return false
}

func (x *FieldDescriptor) GetSensitive() bool {
	if x != nil {
		return x.Sensitive
	}
	return false
}

type CapabilityDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityDescriptor) Reset() {
	*x = CapabilityDescriptor{}
	mi := &file_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityDescriptor) ProtoMessage() {}

func (x *CapabilityDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityDescriptor.ProtoReflect.Descriptor instead.
func (*CapabilityDescriptor) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *CapabilityDescriptor) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CapabilityDescriptor) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CapabilityDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListActionsRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EndpointTemplateId string                 `protobuf:"bytes,1,opt,name=endpoint_template_id,json=endpointTemplateId,proto3" json:"endpoint_template_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListActionsRequest) Reset() {
	*x = ListActionsRequest{}
	mi := &file_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActionsRequest) ProtoMessage() {}

func (x *ListActionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActionsRequest.ProtoReflect.Descriptor instead.
func (*ListActionsRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *ListActionsRequest) GetEndpointTemplateId() string {
	if x != nil {
		return x.EndpointTemplateId
	}
	return ""
}

type ActionSchema struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	InputSchemaJson string                 `protobuf:"bytes,3,opt,name=input_schema_json,json=inputSchemaJson,proto3" json:"input_schema_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ActionSchema) Reset() {
	*x = ActionSchema{}
	mi := &file_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionSchema) ProtoMessage() {}

func (x *ActionSchema) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionSchema.ProtoReflect.Descriptor instead.
func (*ActionSchema) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *ActionSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActionSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActionSchema) GetInputSchemaJson() string {
	if x != nil {
		return x.InputSchemaJson
	}
	return ""
}

type ListActionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*ActionSchema        `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActionsResponse) Reset() {
	*x = ListActionsResponse{}
	mi := &file_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActionsResponse) ProtoMessage() {}

func (x *ListActionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActionsResponse.ProtoReflect.Descriptor instead.
func (*ListActionsResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *ListActionsResponse) GetActions() []*ActionSchema {
	if x != nil {
		return x.Actions
	}
	return nil
}

type ListDatasetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatasetsRequest) Reset() {
	*x = ListDatasetsRequest{}
	mi := &file_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatasetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatasetsRequest) ProtoMessage() {}

func (x *ListDatasetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatasetsRequest.ProtoReflect.Descriptor instead.
func (*ListDatasetsRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *ListDatasetsRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

type DatasetItem struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind                string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	SupportsIncremental bool                   `protobuf:"varint,4,opt,name=supports_incremental,json=supportsIncremental,proto3" json:"supports_incremental,omitempty"`
	CdmModelId          string                 `protobuf:"bytes,5,opt,name=cdm_model_id,json=cdmModelId,proto3" json:"cdm_model_id,omitempty"`
	IngestionStrategy   string                 `protobuf:"bytes,6,opt,name=ingestion_strategy,json=ingestionStrategy,proto3" json:"ingestion_strategy,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DatasetItem) Reset() {
	*x = DatasetItem{}
	mi := &file_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasetItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasetItem) ProtoMessage() {}

func (x *DatasetItem) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasetItem.ProtoReflect.Descriptor instead.
func (*DatasetItem) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *DatasetItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DatasetItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DatasetItem) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *DatasetItem) GetSupportsIncremental() bool {
	if x != nil {
		return x.SupportsIncremental
	}
	return false
}

func (x *DatasetItem) GetCdmModelId() string {
	if x != nil {
		return x.CdmModelId
	}
	return ""
}

func (x *DatasetItem) GetIngestionStrategy() string {
	if x != nil {
		return x.IngestionStrategy
	}
	return ""
}

type ListDatasetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datasets      []*DatasetItem         `protobuf:"bytes,1,rep,name=datasets,proto3" json:"datasets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatasetsResponse) Reset() {
	*x = ListDatasetsResponse{}
	mi := &file_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatasetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatasetsResponse) ProtoMessage() {}

func (x *ListDatasetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatasetsResponse.ProtoReflect.Descriptor instead.
func (*ListDatasetsResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *ListDatasetsResponse) GetDatasets() []*DatasetItem {
	if x != nil {
		return x.Datasets
	}
	return nil
}

type GetSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	DatasetId     string                 `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaRequest) Reset() {
	*x = GetSchemaRequest{}
	mi := &file_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaRequest) ProtoMessage() {}

func (x *GetSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetSchemaRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{13}
}

func (x *GetSchemaRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *GetSchemaRequest) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

type FieldDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DataType      string                 `protobuf:"bytes,2,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Nullable      bool                   `protobuf:"varint,3,opt,name=nullable,proto3" json:"nullable,omitempty"`
	Precision     int32                  `protobuf:"varint,4,opt,name=precision,proto3" json:"precision,omitempty"`
	Scale         int32                  `protobuf:"varint,5,opt,name=scale,proto3" json:"scale,omitempty"`
	Comment       string                 `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldDefinition) Reset() {
	*x = FieldDefinition{}
	mi := &file_gateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldDefinition) ProtoMessage() {}

func (x *FieldDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldDefinition.ProtoReflect.Descriptor instead.
func (*FieldDefinition) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{14}
}

func (x *FieldDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldDefinition) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *FieldDefinition) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

func (x *FieldDefinition) GetPrecision() int32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *FieldDefinition) GetScale() int32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *FieldDefinition) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type Constraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Fields        []string               `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Constraint) Reset() {
	*x = Constraint{}
	mi := &file_gateway_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Constraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Constraint) ProtoMessage() {}

func (x *Constraint) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Constraint.ProtoReflect.Descriptor instead.
func (*Constraint) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{15}
}

func (x *Constraint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Constraint) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Constraint) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type DatasetStatistics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RowCount      int64                  `protobuf:"varint,1,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,2,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Partitions    int32                  `protobuf:"varint,3,opt,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatasetStatistics) Reset() {
	*x = DatasetStatistics{}
	mi := &file_gateway_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasetStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasetStatistics) ProtoMessage() {}

func (x *DatasetStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasetStatistics.ProtoReflect.Descriptor instead.
func (*DatasetStatistics) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{16}
}

func (x *DatasetStatistics) GetRowCount() int64 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

func (x *DatasetStatistics) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *DatasetStatistics) GetPartitions() int32 {
	if x != nil {
		return x.Partitions
	}
	return 0
}

type GetSchemaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*FieldDefinition     `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	Constraints   []*Constraint          `protobuf:"bytes,2,rep,name=constraints,proto3" json:"constraints,omitempty"`
	Statistics    *DatasetStatistics     `protobuf:"bytes,3,opt,name=statistics,proto3" json:"statistics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaResponse) Reset() {
	*x = GetSchemaResponse{}
	mi := &file_gateway_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaResponse) ProtoMessage() {}

func (x *GetSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetSchemaResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{17}
}

func (x *GetSchemaResponse) GetFields() []*FieldDefinition {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *GetSchemaResponse) GetConstraints() []*Constraint {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *GetSchemaResponse) GetStatistics() *DatasetStatistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

type ReadDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	DatasetId     string                 `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	Filter        *structpb.Struct       `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Limit         int64                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDataRequest) Reset() {
	*x = ReadDataRequest{}
	mi := &file_gateway_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDataRequest) ProtoMessage() {}

func (x *ReadDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDataRequest.ProtoReflect.Descriptor instead.
func (*ReadDataRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{18}
}

func (x *ReadDataRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *ReadDataRequest) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *ReadDataRequest) GetFilter() *structpb.Struct {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ReadDataRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ReadDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *structpb.Struct       `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDataResponse) Reset() {
	*x = ReadDataResponse{}
	mi := &file_gateway_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDataResponse) ProtoMessage() {}

func (x *ReadDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDataResponse.ProtoReflect.Descriptor instead.
func (*ReadDataResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{19}
}

func (x *ReadDataResponse) GetRecord() *structpb.Struct {
	if x != nil {
		return x.Record
	}
	return nil
}

type PlanIngestionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	DatasetId     string                 `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	Strategy      string                 `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"` // "adaptive", "linear", "partition"
	Bounds        *structpb.Struct       `protobuf:"bytes,4,opt,name=bounds,proto3" json:"bounds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanIngestionRequest) Reset() {
	*x = PlanIngestionRequest{}
	mi := &file_gateway_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanIngestionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanIngestionRequest) ProtoMessage() {}

func (x *PlanIngestionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanIngestionRequest.ProtoReflect.Descriptor instead.
func (*PlanIngestionRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{20}
}

func (x *PlanIngestionRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *PlanIngestionRequest) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *PlanIngestionRequest) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *PlanIngestionRequest) GetBounds() *structpb.Struct {
	if x != nil {
		return x.Bounds
	}
	return nil
}

type IngestionSlice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SliceId       string                 `protobuf:"bytes,1,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	SliceParams   *structpb.Struct       `protobuf:"bytes,2,opt,name=slice_params,json=sliceParams,proto3" json:"slice_params,omitempty"`
	EstimatedRows int64                  `protobuf:"varint,3,opt,name=estimated_rows,json=estimatedRows,proto3" json:"estimated_rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestionSlice) Reset() {
	*x = IngestionSlice{}
	mi := &file_gateway_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestionSlice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestionSlice) ProtoMessage() {}

func (x *IngestionSlice) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestionSlice.ProtoReflect.Descriptor instead.
func (*IngestionSlice) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{21}
}

func (x *IngestionSlice) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

func (x *IngestionSlice) GetSliceParams() *structpb.Struct {
	if x != nil {
		return x.SliceParams
	}
	return nil
}

func (x *IngestionSlice) GetEstimatedRows() int64 {
	if x != nil {
		return x.EstimatedRows
	}
	return 0
}

type PlanIngestionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slices        []*IngestionSlice      `protobuf:"bytes,1,rep,name=slices,proto3" json:"slices,omitempty"`
	StrategyUsed  string                 `protobuf:"bytes,2,opt,name=strategy_used,json=strategyUsed,proto3" json:"strategy_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanIngestionResponse) Reset() {
	*x = PlanIngestionResponse{}
	mi := &file_gateway_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanIngestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanIngestionResponse) ProtoMessage() {}

func (x *PlanIngestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanIngestionResponse.ProtoReflect.Descriptor instead.
func (*PlanIngestionResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{22}
}

func (x *PlanIngestionResponse) GetSlices() []*IngestionSlice {
	if x != nil {
		return x.Slices
	}
	return nil
}

func (x *PlanIngestionResponse) GetStrategyUsed() string {
	if x != nil {
		return x.StrategyUsed
	}
	return ""
}

type WriteDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	DatasetId     string                 `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"` // "append", "overwrite", "merge"
	LoadDate      string                 `protobuf:"bytes,4,opt,name=load_date,json=loadDate,proto3" json:"load_date,omitempty"`
	Records       []*structpb.Struct     `protobuf:"bytes,5,rep,name=records,proto3" json:"records,omitempty"`
	ExecutionMode ExecutionMode          `protobuf:"varint,6,opt,name=execution_mode,json=executionMode,proto3,enum=ucl.gateway.v1.ExecutionMode" json:"execution_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteDataRequest) Reset() {
	*x = WriteDataRequest{}
	mi := &file_gateway_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteDataRequest) ProtoMessage() {}

func (x *WriteDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteDataRequest.ProtoReflect.Descriptor instead.
func (*WriteDataRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{23}
}

func (x *WriteDataRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *WriteDataRequest) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *WriteDataRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *WriteDataRequest) GetLoadDate() string {
	if x != nil {
		return x.LoadDate
	}
	return ""
}

func (x *WriteDataRequest) GetRecords() []*structpb.Struct {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *WriteDataRequest) GetExecutionMode() ExecutionMode {
	if x != nil {
		return x.ExecutionMode
	}
	return ExecutionMode_EXECUTION_MODE_UNSPECIFIED
}

type WriteDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	RowsWritten   int64                  `protobuf:"varint,2,opt,name=rows_written,json=rowsWritten,proto3" json:"rows_written,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteDataResponse) Reset() {
	*x = WriteDataResponse{}
	mi := &file_gateway_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteDataResponse) ProtoMessage() {}

func (x *WriteDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteDataResponse.ProtoReflect.Descriptor instead.
func (*WriteDataResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{24}
}

func (x *WriteDataResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *WriteDataResponse) GetRowsWritten() int64 {
	if x != nil {
		return x.RowsWritten
	}
	return 0
}

func (x *WriteDataResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetLatestWatermarkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	DatasetId     string                 `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestWatermarkRequest) Reset() {
	*x = GetLatestWatermarkRequest{}
	mi := &file_gateway_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestWatermarkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestWatermarkRequest) ProtoMessage() {}

func (x *GetLatestWatermarkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestWatermarkRequest.ProtoReflect.Descriptor instead.
func (*GetLatestWatermarkRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{25}
}

func (x *GetLatestWatermarkRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *GetLatestWatermarkRequest) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

type GetLatestWatermarkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Watermark     string                 `protobuf:"bytes,1,opt,name=watermark,proto3" json:"watermark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestWatermarkResponse) Reset() {
	*x = GetLatestWatermarkResponse{}
	mi := &file_gateway_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestWatermarkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestWatermarkResponse) ProtoMessage() {}

func (x *GetLatestWatermarkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestWatermarkResponse.ProtoReflect.Descriptor instead.
func (*GetLatestWatermarkResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{26}
}

func (x *GetLatestWatermarkResponse) GetWatermark() string {
	if x != nil {
		return x.Watermark
	}
	return ""
}

type ExecuteActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndpointId    string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	ActionName    string                 `protobuf:"bytes,2,opt,name=action_name,json=actionName,proto3" json:"action_name,omitempty"`
	Parameters    *structpb.Struct       `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
	Mode          ExecutionMode          `protobuf:"varint,4,opt,name=mode,proto3,enum=ucl.gateway.v1.ExecutionMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteActionRequest) Reset() {
	*x = ExecuteActionRequest{}
	mi := &file_gateway_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteActionRequest) ProtoMessage() {}

func (x *ExecuteActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteActionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteActionRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{27}
}

func (x *ExecuteActionRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *ExecuteActionRequest) GetActionName() string {
	if x != nil {
		return x.ActionName
	}
	return ""
}

func (x *ExecuteActionRequest) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ExecuteActionRequest) GetMode() ExecutionMode {
	if x != nil {
		return x.Mode
	}
	return ExecutionMode_EXECUTION_MODE_UNSPECIFIED
}

type ExecuteActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	Result        *structpb.Struct       `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	StatusUrl     string                 `protobuf:"bytes,3,opt,name=status_url,json=statusUrl,proto3" json:"status_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteActionResponse) Reset() {
	*x = ExecuteActionResponse{}
	mi := &file_gateway_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteActionResponse) ProtoMessage() {}

func (x *ExecuteActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteActionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteActionResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{28}
}

func (x *ExecuteActionResponse) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecuteActionResponse) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecuteActionResponse) GetStatusUrl() string {
	if x != nil {
		return x.StatusUrl
	}
	return ""
}

var File_gateway_proto protoreflect.FileDescriptor

const file_gateway_proto_rawDesc = "" +
	"\n" +
	"\rgateway.proto\x12\x0eucl.gateway.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"T\n" +
	"\x14ListEndpointsRequest\x12 \n" +
	"\venvironment\x18\x01 \x01(\tR\venvironment\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\"i\n" +
	"\x13EndpointDescription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\"Z\n" +
	"\x15ListEndpointsResponse\x12A\n" +
	"\tendpoints\x18\x01 \x03(\v2#.ucl.gateway.v1.EndpointDescriptionR\tendpoints\"?\n" +
	"\x1cGetEndpointDescriptorRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\"\xba\x02\n" +
	"\x1dGetEndpointDescriptorResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06family\x18\x02 \x01(\tR\x06family\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06vendor\x18\x04 \x01(\tR\x06vendor\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"categories\x18\x06 \x03(\tR\n" +
	"categories\x127\n" +
	"\x06fields\x18\a \x03(\v2\x1f.ucl.gateway.v1.FieldDescriptorR\x06fields\x12H\n" +
	"\fcapabilities\x18\b \x03(\v2$.ucl.gateway.v1.CapabilityDescriptorR\fcapabilities\"\xb3\x02\n" +
	"\x0fFieldDescriptor\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1d\n" +
	"\n" +
	"value_type\x18\x03 \x01(\tR\tvalueType\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12\x1a\n" +
	"\bsemantic\x18\x05 \x01(\tR\bsemantic\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12 \n" +
	"\vplaceholder\x18\a \x01(\tR\vplaceholder\x12#\n" +
	"\rdefault_value\x18\b \x01(\tR\fdefaultValue\x12\x1a\n" +
	"\badvanced\x18\t \x01(\bR\badvanced\x12\x1c\n" +
	"\tsensitive\x18\n" +
	" \x01(\bR\tsensitive\"`\n" +
	"\x14CapabilityDescriptor\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"F\n" +
	"\x12ListActionsRequest\x120\n" +
	"\x14endpoint_template_id\x18\x01 \x01(\tR\x12endpointTemplateId\"p\n" +
	"\fActionSchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12*\n" +
	"\x11input_schema_json\x18\x03 \x01(\tR\x0finputSchemaJson\"M\n" +
	"\x13ListActionsResponse\x126\n" +
	"\aactions\x18\x01 \x03(\v2\x1c.ucl.gateway.v1.ActionSchemaR\aactions\"6\n" +
	"\x13ListDatasetsRequest\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\"\xc9\x01\n" +
	"\vDatasetItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x121\n" +
	"\x14supports_incremental\x18\x04 \x01(\bR\x13supportsIncremental\x12 \n" +
	"\fcdm_model_id\x18\x05 \x01(\tR\n" +
	"cdmModelId\x12-\n" +
	"\x12ingestion_strategy\x18\x06 \x01(\tR\x11ingestionStrategy\"O\n" +
	"\x14ListDatasetsResponse\x127\n" +
	"\bdatasets\x18\x01 \x03(\v2\x1b.ucl.gateway.v1.DatasetItemR\bdatasets\"R\n" +
	"\x10GetSchemaRequest\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x02 \x01(\tR\tdatasetId\"\xac\x01\n" +
	"\x0fFieldDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tdata_type\x18\x02 \x01(\tR\bdataType\x12\x1a\n" +
	"\bnullable\x18\x03 \x01(\bR\bnullable\x12\x1c\n" +
	"\tprecision\x18\x04 \x01(\x05R\tprecision\x12\x14\n" +
	"\x05scale\x18\x05 \x01(\x05R\x05scale\x12\x18\n" +
	"\acomment\x18\x06 \x01(\tR\acomment\"L\n" +
	"\n" +
	"Constraint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06fields\x18\x03 \x03(\tR\x06fields\"o\n" +
	"\x11DatasetStatistics\x12\x1b\n" +
	"\trow_count\x18\x01 \x01(\x03R\browCount\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x02 \x01(\x03R\tsizeBytes\x12\x1e\n" +
	"\n" +
	"partitions\x18\x03 \x01(\x05R\n" +
	"partitions\"\xcd\x01\n" +
	"\x11GetSchemaResponse\x127\n" +
	"\x06fields\x18\x01 \x03(\v2\x1f.ucl.gateway.v1.FieldDefinitionR\x06fields\x12<\n" +
	"\vconstraints\x18\x02 \x03(\v2\x1a.ucl.gateway.v1.ConstraintR\vconstraints\x12A\n" +
	"\n" +
	"statistics\x18\x03 \x01(\v2!.ucl.gateway.v1.DatasetStatisticsR\n" +
	"statistics\"\x98\x01\n" +
	"\x0fReadDataRequest\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x02 \x01(\tR\tdatasetId\x12/\n" +
	"\x06filter\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06filter\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x03R\x05limit\"C\n" +
	"\x10ReadDataResponse\x12/\n" +
	"\x06record\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06record\"\xa3\x01\n" +
	"\x14PlanIngestionRequest\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x02 \x01(\tR\tdatasetId\x12\x1a\n" +
	"\bstrategy\x18\x03 \x01(\tR\bstrategy\x12/\n" +
	"\x06bounds\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06bounds\"\x8e\x01\n" +
	"\x0eIngestionSlice\x12\x19\n" +
	"\bslice_id\x18\x01 \x01(\tR\asliceId\x12:\n" +
	"\fslice_params\x18\x02 \x01(\v2\x17.google.protobuf.StructR\vsliceParams\x12%\n" +
	"\x0eestimated_rows\x18\x03 \x01(\x03R\restimatedRows\"t\n" +
	"\x15PlanIngestionResponse\x126\n" +
	"\x06slices\x18\x01 \x03(\v2\x1e.ucl.gateway.v1.IngestionSliceR\x06slices\x12#\n" +
	"\rstrategy_used\x18\x02 \x01(\tR\fstrategyUsed\"\xfc\x01\n" +
	"\x10WriteDataRequest\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x02 \x01(\tR\tdatasetId\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\x1b\n" +
	"\tload_date\x18\x04 \x01(\tR\bloadDate\x121\n" +
	"\arecords\x18\x05 \x03(\v2\x17.google.protobuf.StructR\arecords\x12D\n" +
	"\x0eexecution_mode\x18\x06 \x01(\x0e2\x1d.ucl.gateway.v1.ExecutionModeR\rexecutionMode\"m\n" +
	"\x11WriteDataResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12!\n" +
	"\frows_written\x18\x02 \x01(\x03R\vrowsWritten\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"[\n" +
	"\x19GetLatestWatermarkRequest\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x02 \x01(\tR\tdatasetId\":\n" +
	"\x1aGetLatestWatermarkResponse\x12\x1c\n" +
	"\twatermark\x18\x01 \x01(\tR\twatermark\"\xc4\x01\n" +
	"\x14ExecuteActionRequest\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12\x1f\n" +
	"\vaction_name\x18\x02 \x01(\tR\n" +
	"actionName\x127\n" +
	"\n" +
	"parameters\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\x121\n" +
	"\x04mode\x18\x04 \x01(\x0e2\x1d.ucl.gateway.v1.ExecutionModeR\x04mode\"\x8a\x01\n" +
	"\x15ExecuteActionResponse\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12/\n" +
	"\x06result\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06result\x12\x1d\n" +
	"\n" +
	"status_url\x18\x03 \x01(\tR\tstatusUrl*b\n" +
	"\rExecutionMode\x12\x1e\n" +
	"\x1aEXECUTION_MODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13EXECUTION_MODE_SYNC\x10\x01\x12\x18\n" +
	"\x14EXECUTION_MODE_ASYNC\x10\x022\xb5\a\n" +
	"\x0eGatewayService\x12\\\n" +
	"\rListEndpoints\x12$.ucl.gateway.v1.ListEndpointsRequest\x1a%.ucl.gateway.v1.ListEndpointsResponse\x12t\n" +
	"\x15GetEndpointDescriptor\x12,.ucl.gateway.v1.GetEndpointDescriptorRequest\x1a-.ucl.gateway.v1.GetEndpointDescriptorResponse\x12V\n" +
	"\vListActions\x12\".ucl.gateway.v1.ListActionsRequest\x1a#.ucl.gateway.v1.ListActionsResponse\x12Y\n" +
	"\fListDatasets\x12#.ucl.gateway.v1.ListDatasetsRequest\x1a$.ucl.gateway.v1.ListDatasetsResponse\x12P\n" +
	"\tGetSchema\x12 .ucl.gateway.v1.GetSchemaRequest\x1a!.ucl.gateway.v1.GetSchemaResponse\x12O\n" +
	"\bReadData\x12\x1f.ucl.gateway.v1.ReadDataRequest\x1a .ucl.gateway.v1.ReadDataResponse0\x01\x12\\\n" +
	"\rPlanIngestion\x12$.ucl.gateway.v1.PlanIngestionRequest\x1a%.ucl.gateway.v1.PlanIngestionResponse\x12P\n" +
	"\tWriteData\x12 .ucl.gateway.v1.WriteDataRequest\x1a!.ucl.gateway.v1.WriteDataResponse\x12k\n" +
	"\x12GetLatestWatermark\x12).ucl.gateway.v1.GetLatestWatermarkRequest\x1a*.ucl.gateway.v1.GetLatestWatermarkResponse\x12\\\n" +
	"\rExecuteAction\x12$.ucl.gateway.v1.ExecuteActionRequest\x1a%.ucl.gateway.v1.ExecuteActionResponseB6Z4github.com/nucleus/ucl-core/gen/gateway/v1;gatewayv1b\x06proto3"

var (
	file_gateway_proto_rawDescOnce sync.Once
	file_gateway_proto_rawDescData []byte
)

func file_gateway_proto_rawDescGZIP() []byte {
	file_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)))
	})
	return file_gateway_proto_rawDescData
}

var file_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_gateway_proto_goTypes = []any{
	(ExecutionMode)(0),                    // 0: ucl.gateway.v1.ExecutionMode
	(*ListEndpointsRequest)(nil),          // 1: ucl.gateway.v1.ListEndpointsRequest
	(*EndpointDescription)(nil),           // 2: ucl.gateway.v1.EndpointDescription
	(*ListEndpointsResponse)(nil),         // 3: ucl.gateway.v1.ListEndpointsResponse
	(*GetEndpointDescriptorRequest)(nil),  // 4: ucl.gateway.v1.GetEndpointDescriptorRequest
	(*GetEndpointDescriptorResponse)(nil), // 5: ucl.gateway.v1.GetEndpointDescriptorResponse
	(*FieldDescriptor)(nil),               // 6: ucl.gateway.v1.FieldDescriptor
	(*CapabilityDescriptor)(nil),          // 7: ucl.gateway.v1.CapabilityDescriptor
	(*ListActionsRequest)(nil),            // 8: ucl.gateway.v1.ListActionsRequest
	(*ActionSchema)(nil),                  // 9: ucl.gateway.v1.ActionSchema
	(*ListActionsResponse)(nil),           // 10: ucl.gateway.v1.ListActionsResponse
	(*ListDatasetsRequest)(nil),           // 11: ucl.gateway.v1.ListDatasetsRequest
	(*DatasetItem)(nil),                   // 12: ucl.gateway.v1.DatasetItem
	(*ListDatasetsResponse)(nil),          // 13: ucl.gateway.v1.ListDatasetsResponse
	(*GetSchemaRequest)(nil),              // 14: ucl.gateway.v1.GetSchemaRequest
	(*FieldDefinition)(nil),               // 15: ucl.gateway.v1.FieldDefinition
	(*Constraint)(nil),                    // 16: ucl.gateway.v1.Constraint
	(*DatasetStatistics)(nil),             // 17: ucl.gateway.v1.DatasetStatistics
	(*GetSchemaResponse)(nil),             // 18: ucl.gateway.v1.GetSchemaResponse
	(*ReadDataRequest)(nil),               // 19: ucl.gateway.v1.ReadDataRequest
	(*ReadDataResponse)(nil),              // 20: ucl.gateway.v1.ReadDataResponse
	(*PlanIngestionRequest)(nil),          // 21: ucl.gateway.v1.PlanIngestionRequest
	(*IngestionSlice)(nil),                // 22: ucl.gateway.v1.IngestionSlice
	(*PlanIngestionResponse)(nil),         // 23: ucl.gateway.v1.PlanIngestionResponse
	(*WriteDataRequest)(nil),              // 24: ucl.gateway.v1.WriteDataRequest
	(*WriteDataResponse)(nil),             // 25: ucl.gateway.v1.WriteDataResponse
	(*GetLatestWatermarkRequest)(nil),     // 26: ucl.gateway.v1.GetLatestWatermarkRequest
	(*GetLatestWatermarkResponse)(nil),    // 27: ucl.gateway.v1.GetLatestWatermarkResponse
	(*ExecuteActionRequest)(nil),          // 28: ucl.gateway.v1.ExecuteActionRequest
	(*ExecuteActionResponse)(nil),         // 29: ucl.gateway.v1.ExecuteActionResponse
	(*structpb.Struct)(nil),               // 30: google.protobuf.Struct
}
var file_gateway_proto_depIdxs = []int32{
	2,  // 0: ucl.gateway.v1.ListEndpointsResponse.endpoints:type_name -> ucl.gateway.v1.EndpointDescription
	6,  // 1: ucl.gateway.v1.GetEndpointDescriptorResponse.fields:type_name -> ucl.gateway.v1.FieldDescriptor
	7,  // 2: ucl.gateway.v1.GetEndpointDescriptorResponse.capabilities:type_name -> ucl.gateway.v1.CapabilityDescriptor
	9,  // 3: ucl.gateway.v1.ListActionsResponse.actions:type_name -> ucl.gateway.v1.ActionSchema
	12, // 4: ucl.gateway.v1.ListDatasetsResponse.datasets:type_name -> ucl.gateway.v1.DatasetItem
	15, // 5: ucl.gateway.v1.GetSchemaResponse.fields:type_name -> ucl.gateway.v1.FieldDefinition
	16, // 6: ucl.gateway.v1.GetSchemaResponse.constraints:type_name -> ucl.gateway.v1.Constraint
	17, // 7: ucl.gateway.v1.GetSchemaResponse.statistics:type_name -> ucl.gateway.v1.DatasetStatistics
	30, // 8: ucl.gateway.v1.ReadDataRequest.filter:type_name -> google.protobuf.Struct
	30, // 9: ucl.gateway.v1.ReadDataResponse.record:type_name -> google.protobuf.Struct
	30, // 10: ucl.gateway.v1.PlanIngestionRequest.bounds:type_name -> google.protobuf.Struct
	30, // 11: ucl.gateway.v1.IngestionSlice.slice_params:type_name -> google.protobuf.Struct
	22, // 12: ucl.gateway.v1.PlanIngestionResponse.slices:type_name -> ucl.gateway.v1.IngestionSlice
	30, // 13: ucl.gateway.v1.WriteDataRequest.records:type_name -> google.protobuf.Struct
	0,  // 14: ucl.gateway.v1.WriteDataRequest.execution_mode:type_name -> ucl.gateway.v1.ExecutionMode
	30, // 15: ucl.gateway.v1.ExecuteActionRequest.parameters:type_name -> google.protobuf.Struct
	0,  // 16: ucl.gateway.v1.ExecuteActionRequest.mode:type_name -> ucl.gateway.v1.ExecutionMode
	30, // 17: ucl.gateway.v1.ExecuteActionResponse.result:type_name -> google.protobuf.Struct
	1,  // 18: ucl.gateway.v1.GatewayService.ListEndpoints:input_type -> ucl.gateway.v1.ListEndpointsRequest
	4,  // 19: ucl.gateway.v1.GatewayService.GetEndpointDescriptor:input_type -> ucl.gateway.v1.GetEndpointDescriptorRequest
	8,  // 20: ucl.gateway.v1.GatewayService.ListActions:input_type -> ucl.gateway.v1.ListActionsRequest
	11, // 21: ucl.gateway.v1.GatewayService.ListDatasets:input_type -> ucl.gateway.v1.ListDatasetsRequest
	14, // 22: ucl.gateway.v1.GatewayService.GetSchema:input_type -> ucl.gateway.v1.GetSchemaRequest
	19, // 23: ucl.gateway.v1.GatewayService.ReadData:input_type -> ucl.gateway.v1.ReadDataRequest
	21, // 24: ucl.gateway.v1.GatewayService.PlanIngestion:input_type -> ucl.gateway.v1.PlanIngestionRequest
	24, // 25: ucl.gateway.v1.GatewayService.WriteData:input_type -> ucl.gateway.v1.WriteDataRequest
	26, // 26: ucl.gateway.v1.GatewayService.GetLatestWatermark:input_type -> ucl.gateway.v1.GetLatestWatermarkRequest
	28, // 27: ucl.gateway.v1.GatewayService.ExecuteAction:input_type -> ucl.gateway.v1.ExecuteActionRequest
	3,  // 28: ucl.gateway.v1.GatewayService.ListEndpoints:output_type -> ucl.gateway.v1.ListEndpointsResponse
	5,  // 29: ucl.gateway.v1.GatewayService.GetEndpointDescriptor:output_type -> ucl.gateway.v1.GetEndpointDescriptorResponse
	10, // 30: ucl.gateway.v1.GatewayService.ListActions:output_type -> ucl.gateway.v1.ListActionsResponse
	13, // 31: ucl.gateway.v1.GatewayService.ListDatasets:output_type -> ucl.gateway.v1.ListDatasetsResponse
	18, // 32: ucl.gateway.v1.GatewayService.GetSchema:output_type -> ucl.gateway.v1.GetSchemaResponse
	20, // 33: ucl.gateway.v1.GatewayService.ReadData:output_type -> ucl.gateway.v1.ReadDataResponse
	23, // 34: ucl.gateway.v1.GatewayService.PlanIngestion:output_type -> ucl.gateway.v1.PlanIngestionResponse
	25, // 35: ucl.gateway.v1.GatewayService.WriteData:output_type -> ucl.gateway.v1.WriteDataResponse
	27, // 36: ucl.gateway.v1.GatewayService.GetLatestWatermark:output_type -> ucl.gateway.v1.GetLatestWatermarkResponse
	29, // 37: ucl.gateway.v1.GatewayService.ExecuteAction:output_type -> ucl.gateway.v1.ExecuteActionResponse
	28, // [28:38] is the sub-list for method output_type
	18, // [18:28] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_gateway_proto_init() }
func file_gateway_proto_init() {
	if File_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_proto_depIdxs,
		EnumInfos:         file_gateway_proto_enumTypes,
		MessageInfos:      file_gateway_proto_msgTypes,
	}.Build()
	File_gateway_proto = out.File
	file_gateway_proto_goTypes = nil
	file_gateway_proto_depIdxs = nil
}
