// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: gateway.proto

package gatewaypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayService_ListEndpoints_FullMethodName         = "/ucl.gateway.v1.GatewayService/ListEndpoints"
	GatewayService_GetEndpointDescriptor_FullMethodName = "/ucl.gateway.v1.GatewayService/GetEndpointDescriptor"
	GatewayService_ListActions_FullMethodName           = "/ucl.gateway.v1.GatewayService/ListActions"
	GatewayService_ListDatasets_FullMethodName          = "/ucl.gateway.v1.GatewayService/ListDatasets"
	GatewayService_GetSchema_FullMethodName             = "/ucl.gateway.v1.GatewayService/GetSchema"
	GatewayService_ReadData_FullMethodName              = "/ucl.gateway.v1.GatewayService/ReadData"
	GatewayService_PlanIngestion_FullMethodName         = "/ucl.gateway.v1.GatewayService/PlanIngestion"
	GatewayService_WriteData_FullMethodName             = "/ucl.gateway.v1.GatewayService/WriteData"
	GatewayService_GetLatestWatermark_FullMethodName    = "/ucl.gateway.v1.GatewayService/GetLatestWatermark"
	GatewayService_ExecuteAction_FullMethodName         = "/ucl.gateway.v1.GatewayService/ExecuteAction"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The Universal Gateway Service
type GatewayServiceClient interface {
	// --- Discovery ---
	ListEndpoints(ctx context.Context, in *ListEndpointsRequest, opts ...grpc.CallOption) (*ListEndpointsResponse, error)
	GetEndpointDescriptor(ctx context.Context, in *GetEndpointDescriptorRequest, opts ...grpc.CallOption) (*GetEndpointDescriptorResponse, error)
	ListActions(ctx context.Context, in *ListActionsRequest, opts ...grpc.CallOption) (*ListActionsResponse, error)
	ListDatasets(ctx context.Context, in *ListDatasetsRequest, opts ...grpc.CallOption) (*ListDatasetsResponse, error)
	// --- Data Plane: Source ---
	GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error)
	ReadData(ctx context.Context, in *ReadDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadDataResponse], error)
	PlanIngestion(ctx context.Context, in *PlanIngestionRequest, opts ...grpc.CallOption) (*PlanIngestionResponse, error)
	// --- Data Plane: Sink (NEW) ---
	WriteData(ctx context.Context, in *WriteDataRequest, opts ...grpc.CallOption) (*WriteDataResponse, error)
	GetLatestWatermark(ctx context.Context, in *GetLatestWatermarkRequest, opts ...grpc.CallOption) (*GetLatestWatermarkResponse, error)
	// --- Control Plane ---
	ExecuteAction(ctx context.Context, in *ExecuteActionRequest, opts ...grpc.CallOption) (*ExecuteActionResponse, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) ListEndpoints(ctx context.Context, in *ListEndpointsRequest, opts ...grpc.CallOption) (*ListEndpointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEndpointsResponse)
	err := c.cc.Invoke(ctx, GatewayService_ListEndpoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetEndpointDescriptor(ctx context.Context, in *GetEndpointDescriptorRequest, opts ...grpc.CallOption) (*GetEndpointDescriptorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEndpointDescriptorResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetEndpointDescriptor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ListActions(ctx context.Context, in *ListActionsRequest, opts ...grpc.CallOption) (*ListActionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActionsResponse)
	err := c.cc.Invoke(ctx, GatewayService_ListActions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ListDatasets(ctx context.Context, in *ListDatasetsRequest, opts ...grpc.CallOption) (*ListDatasetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDatasetsResponse)
	err := c.cc.Invoke(ctx, GatewayService_ListDatasets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetSchema(ctx context.Context, in *GetSchemaRequest, opts ...grpc.CallOption) (*GetSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSchemaResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ReadData(ctx context.Context, in *ReadDataRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GatewayService_ServiceDesc.Streams[0], GatewayService_ReadData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadDataRequest, ReadDataResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_ReadDataClient = grpc.ServerStreamingClient[ReadDataResponse]

func (c *gatewayServiceClient) PlanIngestion(ctx context.Context, in *PlanIngestionRequest, opts ...grpc.CallOption) (*PlanIngestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlanIngestionResponse)
	err := c.cc.Invoke(ctx, GatewayService_PlanIngestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) WriteData(ctx context.Context, in *WriteDataRequest, opts ...grpc.CallOption) (*WriteDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteDataResponse)
	err := c.cc.Invoke(ctx, GatewayService_WriteData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) GetLatestWatermark(ctx context.Context, in *GetLatestWatermarkRequest, opts ...grpc.CallOption) (*GetLatestWatermarkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLatestWatermarkResponse)
	err := c.cc.Invoke(ctx, GatewayService_GetLatestWatermark_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) ExecuteAction(ctx context.Context, in *ExecuteActionRequest, opts ...grpc.CallOption) (*ExecuteActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteActionResponse)
	err := c.cc.Invoke(ctx, GatewayService_ExecuteAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility.
//
// The Universal Gateway Service
type GatewayServiceServer interface {
	// --- Discovery ---
	ListEndpoints(context.Context, *ListEndpointsRequest) (*ListEndpointsResponse, error)
	GetEndpointDescriptor(context.Context, *GetEndpointDescriptorRequest) (*GetEndpointDescriptorResponse, error)
	ListActions(context.Context, *ListActionsRequest) (*ListActionsResponse, error)
	ListDatasets(context.Context, *ListDatasetsRequest) (*ListDatasetsResponse, error)
	// --- Data Plane: Source ---
	GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error)
	ReadData(*ReadDataRequest, grpc.ServerStreamingServer[ReadDataResponse]) error
	PlanIngestion(context.Context, *PlanIngestionRequest) (*PlanIngestionResponse, error)
	// --- Data Plane: Sink (NEW) ---
	WriteData(context.Context, *WriteDataRequest) (*WriteDataResponse, error)
	GetLatestWatermark(context.Context, *GetLatestWatermarkRequest) (*GetLatestWatermarkResponse, error)
	// --- Control Plane ---
	ExecuteAction(context.Context, *ExecuteActionRequest) (*ExecuteActionResponse, error)
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServiceServer struct{}

func (UnimplementedGatewayServiceServer) ListEndpoints(context.Context, *ListEndpointsRequest) (*ListEndpointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEndpoints not implemented")
}
func (UnimplementedGatewayServiceServer) GetEndpointDescriptor(context.Context, *GetEndpointDescriptorRequest) (*GetEndpointDescriptorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEndpointDescriptor not implemented")
}
func (UnimplementedGatewayServiceServer) ListActions(context.Context, *ListActionsRequest) (*ListActionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActions not implemented")
}
func (UnimplementedGatewayServiceServer) ListDatasets(context.Context, *ListDatasetsRequest) (*ListDatasetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDatasets not implemented")
}
func (UnimplementedGatewayServiceServer) GetSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSchema not implemented")
}
func (UnimplementedGatewayServiceServer) ReadData(*ReadDataRequest, grpc.ServerStreamingServer[ReadDataResponse]) error {
	return status.Error(codes.Unimplemented, "method ReadData not implemented")
}
func (UnimplementedGatewayServiceServer) PlanIngestion(context.Context, *PlanIngestionRequest) (*PlanIngestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlanIngestion not implemented")
}
func (UnimplementedGatewayServiceServer) WriteData(context.Context, *WriteDataRequest) (*WriteDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteData not implemented")
}
func (UnimplementedGatewayServiceServer) GetLatestWatermark(context.Context, *GetLatestWatermarkRequest) (*GetLatestWatermarkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestWatermark not implemented")
}
func (UnimplementedGatewayServiceServer) ExecuteAction(context.Context, *ExecuteActionRequest) (*ExecuteActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteAction not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}
func (UnimplementedGatewayServiceServer) testEmbeddedByValue()                        {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_ListEndpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEndpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ListEndpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ListEndpoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ListEndpoints(ctx, req.(*ListEndpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetEndpointDescriptor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEndpointDescriptorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetEndpointDescriptor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetEndpointDescriptor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetEndpointDescriptor(ctx, req.(*GetEndpointDescriptorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ListActions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ListActions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ListActions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ListActions(ctx, req.(*ListActionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ListDatasets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDatasetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ListDatasets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ListDatasets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ListDatasets(ctx, req.(*ListDatasetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetSchema(ctx, req.(*GetSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ReadData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadDataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GatewayServiceServer).ReadData(m, &grpc.GenericServerStream[ReadDataRequest, ReadDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GatewayService_ReadDataServer = grpc.ServerStreamingServer[ReadDataResponse]

func _GatewayService_PlanIngestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlanIngestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).PlanIngestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_PlanIngestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).PlanIngestion(ctx, req.(*PlanIngestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_WriteData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).WriteData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_WriteData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).WriteData(ctx, req.(*WriteDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_GetLatestWatermark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestWatermarkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).GetLatestWatermark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_GetLatestWatermark_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).GetLatestWatermark(ctx, req.(*GetLatestWatermarkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_ExecuteAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).ExecuteAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_ExecuteAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).ExecuteAction(ctx, req.(*ExecuteActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ucl.gateway.v1.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListEndpoints",
			Handler:    _GatewayService_ListEndpoints_Handler,
		},
		{
			MethodName: "GetEndpointDescriptor",
			Handler:    _GatewayService_GetEndpointDescriptor_Handler,
		},
		{
			MethodName: "ListActions",
			Handler:    _GatewayService_ListActions_Handler,
		},
		{
			MethodName: "ListDatasets",
			Handler:    _GatewayService_ListDatasets_Handler,
		},
		{
			MethodName: "GetSchema",
			Handler:    _GatewayService_GetSchema_Handler,
		},
		{
			MethodName: "PlanIngestion",
			Handler:    _GatewayService_PlanIngestion_Handler,
		},
		{
			MethodName: "WriteData",
			Handler:    _GatewayService_WriteData_Handler,
		},
		{
			MethodName: "GetLatestWatermark",
			Handler:    _GatewayService_GetLatestWatermark_Handler,
		},
		{
			MethodName: "ExecuteAction",
			Handler:    _GatewayService_ExecuteAction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadData",
			Handler:       _GatewayService_ReadData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gateway.proto",
}
