// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: vector.proto

package vectorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Entry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProfileId      string                 `protobuf:"bytes,3,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	NodeId         string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SourceFamily   string                 `protobuf:"bytes,5,opt,name=source_family,json=sourceFamily,proto3" json:"source_family,omitempty"`
	ArtifactId     string                 `protobuf:"bytes,6,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	RunId          string                 `protobuf:"bytes,7,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	SinkEndpointId string                 `protobuf:"bytes,8,opt,name=sink_endpoint_id,json=sinkEndpointId,proto3" json:"sink_endpoint_id,omitempty"`
	DatasetSlug    string                 `protobuf:"bytes,9,opt,name=dataset_slug,json=datasetSlug,proto3" json:"dataset_slug,omitempty"`
	EntityKind     string                 `protobuf:"bytes,10,opt,name=entity_kind,json=entityKind,proto3" json:"entity_kind,omitempty"`
	Labels         []string               `protobuf:"bytes,11,rep,name=labels,proto3" json:"labels,omitempty"`
	Tags           []string               `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	ContentText    string                 `protobuf:"bytes,13,opt,name=content_text,json=contentText,proto3" json:"content_text,omitempty"`
	Metadata       *structpb.Struct       `protobuf:"bytes,14,opt,name=metadata,proto3" json:"metadata,omitempty"`
	RawPayload     *structpb.Struct       `protobuf:"bytes,15,opt,name=raw_payload,json=rawPayload,proto3" json:"raw_payload,omitempty"`
	RawMetadata    *structpb.Struct       `protobuf:"bytes,16,opt,name=raw_metadata,json=rawMetadata,proto3" json:"raw_metadata,omitempty"`
	Embedding      []float32              `protobuf:"fixed32,17,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_vector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_vector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_vector_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Entry) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Entry) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *Entry) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Entry) GetSourceFamily() string {
	if x != nil {
		return x.SourceFamily
	}
	return ""
}

func (x *Entry) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *Entry) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Entry) GetSinkEndpointId() string {
	if x != nil {
		return x.SinkEndpointId
	}
	return ""
}

func (x *Entry) GetDatasetSlug() string {
	if x != nil {
		return x.DatasetSlug
	}
	return ""
}

func (x *Entry) GetEntityKind() string {
	if x != nil {
		return x.EntityKind
	}
	return ""
}

func (x *Entry) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Entry) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Entry) GetContentText() string {
	if x != nil {
		return x.ContentText
	}
	return ""
}

func (x *Entry) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Entry) GetRawPayload() *structpb.Struct {
	if x != nil {
		return x.RawPayload
	}
	return nil
}

func (x *Entry) GetRawMetadata() *structpb.Struct {
	if x != nil {
		return x.RawMetadata
	}
	return nil
}

func (x *Entry) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type UpsertEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertEntriesRequest) Reset() {
	*x = UpsertEntriesRequest{}
	mi := &file_vector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertEntriesRequest) ProtoMessage() {}

func (x *UpsertEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertEntriesRequest.ProtoReflect.Descriptor instead.
func (*UpsertEntriesRequest) Descriptor() ([]byte, []int) {
	return file_vector_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertEntriesRequest) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type UpsertEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Upserted      int32                  `protobuf:"varint,1,opt,name=upserted,proto3" json:"upserted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertEntriesResponse) Reset() {
	*x = UpsertEntriesResponse{}
	mi := &file_vector_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertEntriesResponse) ProtoMessage() {}

func (x *UpsertEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertEntriesResponse.ProtoReflect.Descriptor instead.
func (*UpsertEntriesResponse) Descriptor() ([]byte, []int) {
	return file_vector_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertEntriesResponse) GetUpserted() int32 {
	if x != nil {
		return x.Upserted
	}
	return 0
}

type SearchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProfileIds     []string               `protobuf:"bytes,3,rep,name=profile_ids,json=profileIds,proto3" json:"profile_ids,omitempty"`
	SourceFamily   string                 `protobuf:"bytes,4,opt,name=source_family,json=sourceFamily,proto3" json:"source_family,omitempty"`
	ArtifactId     string                 `protobuf:"bytes,5,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	RunId          string                 `protobuf:"bytes,6,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	SinkEndpointId string                 `protobuf:"bytes,7,opt,name=sink_endpoint_id,json=sinkEndpointId,proto3" json:"sink_endpoint_id,omitempty"`
	DatasetSlug    string                 `protobuf:"bytes,8,opt,name=dataset_slug,json=datasetSlug,proto3" json:"dataset_slug,omitempty"`
	EntityKinds    []string               `protobuf:"bytes,9,rep,name=entity_kinds,json=entityKinds,proto3" json:"entity_kinds,omitempty"`
	Labels         []string               `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty"`
	Tags           []string               `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	TopK           int32                  `protobuf:"varint,12,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Embedding      []float32              `protobuf:"fixed32,13,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_vector_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_vector_proto_rawDescGZIP(), []int{3}
}

func (x *SearchRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SearchRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SearchRequest) GetProfileIds() []string {
	if x != nil {
		return x.ProfileIds
	}
	return nil
}

func (x *SearchRequest) GetSourceFamily() string {
	if x != nil {
		return x.SourceFamily
	}
	return ""
}

func (x *SearchRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *SearchRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *SearchRequest) GetSinkEndpointId() string {
	if x != nil {
		return x.SinkEndpointId
	}
	return ""
}

func (x *SearchRequest) GetDatasetSlug() string {
	if x != nil {
		return x.DatasetSlug
	}
	return ""
}

func (x *SearchRequest) GetEntityKinds() []string {
	if x != nil {
		return x.EntityKinds
	}
	return nil
}

func (x *SearchRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *SearchRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SearchRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchRequest) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type SearchHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ProfileId     string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	ContentText   string                 `protobuf:"bytes,4,opt,name=content_text,json=contentText,proto3" json:"content_text,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHit) Reset() {
	*x = SearchHit{}
	mi := &file_vector_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHit) ProtoMessage() {}

func (x *SearchHit) ProtoReflect() protoreflect.Message {
	mi := &file_vector_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHit.ProtoReflect.Descriptor instead.
func (*SearchHit) Descriptor() ([]byte, []int) {
	return file_vector_proto_rawDescGZIP(), []int{4}
}

func (x *SearchHit) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SearchHit) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *SearchHit) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchHit) GetContentText() string {
	if x != nil {
		return x.ContentText
	}
	return ""
}

func (x *SearchHit) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hits          []*SearchHit           `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_vector_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_vector_proto_rawDescGZIP(), []int{5}
}

func (x *SearchResponse) GetHits() []*SearchHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

type DeleteByArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ArtifactId    string                 `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	RunId         string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteByArtifactRequest) Reset() {
	*x = DeleteByArtifactRequest{}
	mi := &file_vector_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteByArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteByArtifactRequest) ProtoMessage() {}

func (x *DeleteByArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteByArtifactRequest.ProtoReflect.Descriptor instead.
func (*DeleteByArtifactRequest) Descriptor() ([]byte, []int) {
	return file_vector_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteByArtifactRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteByArtifactRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *DeleteByArtifactRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type DeleteByArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteByArtifactResponse) Reset() {
	*x = DeleteByArtifactResponse{}
	mi := &file_vector_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteByArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteByArtifactResponse) ProtoMessage() {}

func (x *DeleteByArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteByArtifactResponse.ProtoReflect.Descriptor instead.
func (*DeleteByArtifactResponse) Descriptor() ([]byte, []int) {
	return file_vector_proto_rawDescGZIP(), []int{7}
}

type ListEntriesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ProjectId      string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ProfileIds     []string               `protobuf:"bytes,3,rep,name=profile_ids,json=profileIds,proto3" json:"profile_ids,omitempty"`
	SourceFamily   string                 `protobuf:"bytes,4,opt,name=source_family,json=sourceFamily,proto3" json:"source_family,omitempty"`
	ArtifactId     string                 `protobuf:"bytes,5,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	RunId          string                 `protobuf:"bytes,6,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	SinkEndpointId string                 `protobuf:"bytes,7,opt,name=sink_endpoint_id,json=sinkEndpointId,proto3" json:"sink_endpoint_id,omitempty"`
	DatasetSlug    string                 `protobuf:"bytes,8,opt,name=dataset_slug,json=datasetSlug,proto3" json:"dataset_slug,omitempty"`
	EntityKinds    []string               `protobuf:"bytes,9,rep,name=entity_kinds,json=entityKinds,proto3" json:"entity_kinds,omitempty"`
	Labels         []string               `protobuf:"bytes,10,rep,name=labels,proto3" json:"labels,omitempty"`
	Tags           []string               `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	Limit          int32                  `protobuf:"varint,12,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListEntriesRequest) Reset() {
	*x = ListEntriesRequest{}
	mi := &file_vector_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesRequest) ProtoMessage() {}

func (x *ListEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vector_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListEntriesRequest) Descriptor() ([]byte, []int) {
	return file_vector_proto_rawDescGZIP(), []int{8}
}

func (x *ListEntriesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListEntriesRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListEntriesRequest) GetProfileIds() []string {
	if x != nil {
		return x.ProfileIds
	}
	return nil
}

func (x *ListEntriesRequest) GetSourceFamily() string {
	if x != nil {
		return x.SourceFamily
	}
	return ""
}

func (x *ListEntriesRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ListEntriesRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ListEntriesRequest) GetSinkEndpointId() string {
	if x != nil {
		return x.SinkEndpointId
	}
	return ""
}

func (x *ListEntriesRequest) GetDatasetSlug() string {
	if x != nil {
		return x.DatasetSlug
	}
	return ""
}

func (x *ListEntriesRequest) GetEntityKinds() []string {
	if x != nil {
		return x.EntityKinds
	}
	return nil
}

func (x *ListEntriesRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ListEntriesRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListEntriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesResponse) Reset() {
	*x = ListEntriesResponse{}
	mi := &file_vector_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesResponse) ProtoMessage() {}

func (x *ListEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vector_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListEntriesResponse) Descriptor() ([]byte, []int) {
	return file_vector_proto_rawDescGZIP(), []int{9}
}

func (x *ListEntriesResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_vector_proto protoreflect.FileDescriptor

const file_vector_proto_rawDesc = "" +
	"\n" +
	"\fvector.proto\x12\x06vector\x1a\x1cgoogle/protobuf/struct.proto\"\xde\x04\n" +
	"\x05Entry\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x03 \x01(\tR\tprofileId\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12#\n" +
	"\rsource_family\x18\x05 \x01(\tR\fsourceFamily\x12\x1f\n" +
	"\vartifact_id\x18\x06 \x01(\tR\n" +
	"artifactId\x12\x15\n" +
	"\x06run_id\x18\a \x01(\tR\x05runId\x12(\n" +
	"\x10sink_endpoint_id\x18\b \x01(\tR\x0esinkEndpointId\x12!\n" +
	"\fdataset_slug\x18\t \x01(\tR\vdatasetSlug\x12\x1f\n" +
	"\ventity_kind\x18\n" +
	" \x01(\tR\n" +
	"entityKind\x12\x16\n" +
	"\x06labels\x18\v \x03(\tR\x06labels\x12\x12\n" +
	"\x04tags\x18\f \x03(\tR\x04tags\x12!\n" +
	"\fcontent_text\x18\r \x01(\tR\vcontentText\x123\n" +
	"\bmetadata\x18\x0e \x01(\v2\x17.google.protobuf.StructR\bmetadata\x128\n" +
	"\vraw_payload\x18\x0f \x01(\v2\x17.google.protobuf.StructR\n" +
	"rawPayload\x12:\n" +
	"\fraw_metadata\x18\x10 \x01(\v2\x17.google.protobuf.StructR\vrawMetadata\x12\x1c\n" +
	"\tembedding\x18\x11 \x03(\x02R\tembedding\"?\n" +
	"\x14UpsertEntriesRequest\x12'\n" +
	"\aentries\x18\x01 \x03(\v2\r.vector.EntryR\aentries\"3\n" +
	"\x15UpsertEntriesResponse\x12\x1a\n" +
	"\bupserted\x18\x01 \x01(\x05R\bupserted\"\x98\x03\n" +
	"\rSearchRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vprofile_ids\x18\x03 \x03(\tR\n" +
	"profileIds\x12#\n" +
	"\rsource_family\x18\x04 \x01(\tR\fsourceFamily\x12\x1f\n" +
	"\vartifact_id\x18\x05 \x01(\tR\n" +
	"artifactId\x12\x15\n" +
	"\x06run_id\x18\x06 \x01(\tR\x05runId\x12(\n" +
	"\x10sink_endpoint_id\x18\a \x01(\tR\x0esinkEndpointId\x12!\n" +
	"\fdataset_slug\x18\b \x01(\tR\vdatasetSlug\x12!\n" +
	"\fentity_kinds\x18\t \x03(\tR\ventityKinds\x12\x16\n" +
	"\x06labels\x18\n" +
	" \x03(\tR\x06labels\x12\x12\n" +
	"\x04tags\x18\v \x03(\tR\x04tags\x12\x13\n" +
	"\x05top_k\x18\f \x01(\x05R\x04topK\x12\x1c\n" +
	"\tembedding\x18\r \x03(\x02R\tembedding\"\xb1\x01\n" +
	"\tSearchHit\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\x12!\n" +
	"\fcontent_text\x18\x04 \x01(\tR\vcontentText\x123\n" +
	"\bmetadata\x18\x05 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"7\n" +
	"\x0eSearchResponse\x12%\n" +
	"\x04hits\x18\x01 \x03(\v2\x11.vector.SearchHitR\x04hits\"n\n" +
	"\x17DeleteByArtifactRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vartifact_id\x18\x02 \x01(\tR\n" +
	"artifactId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\"\x1a\n" +
	"\x18DeleteByArtifactResponse\"\x80\x03\n" +
	"\x12ListEntriesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x1f\n" +
	"\vprofile_ids\x18\x03 \x03(\tR\n" +
	"profileIds\x12#\n" +
	"\rsource_family\x18\x04 \x01(\tR\fsourceFamily\x12\x1f\n" +
	"\vartifact_id\x18\x05 \x01(\tR\n" +
	"artifactId\x12\x15\n" +
	"\x06run_id\x18\x06 \x01(\tR\x05runId\x12(\n" +
	"\x10sink_endpoint_id\x18\a \x01(\tR\x0esinkEndpointId\x12!\n" +
	"\fdataset_slug\x18\b \x01(\tR\vdatasetSlug\x12!\n" +
	"\fentity_kinds\x18\t \x03(\tR\ventityKinds\x12\x16\n" +
	"\x06labels\x18\n" +
	" \x03(\tR\x06labels\x12\x12\n" +
	"\x04tags\x18\v \x03(\tR\x04tags\x12\x14\n" +
	"\x05limit\x18\f \x01(\x05R\x05limit\">\n" +
	"\x13ListEntriesResponse\x12'\n" +
	"\aentries\x18\x01 \x03(\v2\r.vector.EntryR\aentries2\xb5\x02\n" +
	"\rVectorService\x12L\n" +
	"\rUpsertEntries\x12\x1c.vector.UpsertEntriesRequest\x1a\x1d.vector.UpsertEntriesResponse\x127\n" +
	"\x06Search\x12\x15.vector.SearchRequest\x1a\x16.vector.SearchResponse\x12U\n" +
	"\x10DeleteByArtifact\x12\x1f.vector.DeleteByArtifactRequest\x1a .vector.DeleteByArtifactResponse\x12F\n" +
	"\vListEntries\x12\x1a.vector.ListEntriesRequest\x1a\x1b.vector.ListEntriesResponseBJZHgithub.com/antigravity/go-agent-service/internal/store/vectorpb;vectorpbb\x06proto3"

var (
	file_vector_proto_rawDescOnce sync.Once
	file_vector_proto_rawDescData []byte
)

func file_vector_proto_rawDescGZIP() []byte {
	file_vector_proto_rawDescOnce.Do(func() {
		file_vector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vector_proto_rawDesc), len(file_vector_proto_rawDesc)))
	})
	return file_vector_proto_rawDescData
}

var file_vector_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_vector_proto_goTypes = []any{
	(*Entry)(nil),                    // 0: vector.Entry
	(*UpsertEntriesRequest)(nil),     // 1: vector.UpsertEntriesRequest
	(*UpsertEntriesResponse)(nil),    // 2: vector.UpsertEntriesResponse
	(*SearchRequest)(nil),            // 3: vector.SearchRequest
	(*SearchHit)(nil),                // 4: vector.SearchHit
	(*SearchResponse)(nil),           // 5: vector.SearchResponse
	(*DeleteByArtifactRequest)(nil),  // 6: vector.DeleteByArtifactRequest
	(*DeleteByArtifactResponse)(nil), // 7: vector.DeleteByArtifactResponse
	(*ListEntriesRequest)(nil),       // 8: vector.ListEntriesRequest
	(*ListEntriesResponse)(nil),      // 9: vector.ListEntriesResponse
	(*structpb.Struct)(nil),          // 10: google.protobuf.Struct
}
var file_vector_proto_depIdxs = []int32{
	10, // 0: vector.Entry.metadata:type_name -> google.protobuf.Struct
	10, // 1: vector.Entry.raw_payload:type_name -> google.protobuf.Struct
	10, // 2: vector.Entry.raw_metadata:type_name -> google.protobuf.Struct
	0,  // 3: vector.UpsertEntriesRequest.entries:type_name -> vector.Entry
	10, // 4: vector.SearchHit.metadata:type_name -> google.protobuf.Struct
	4,  // 5: vector.SearchResponse.hits:type_name -> vector.SearchHit
	0,  // 6: vector.ListEntriesResponse.entries:type_name -> vector.Entry
	1,  // 7: vector.VectorService.UpsertEntries:input_type -> vector.UpsertEntriesRequest
	3,  // 8: vector.VectorService.Search:input_type -> vector.SearchRequest
	6,  // 9: vector.VectorService.DeleteByArtifact:input_type -> vector.DeleteByArtifactRequest
	8,  // 10: vector.VectorService.ListEntries:input_type -> vector.ListEntriesRequest
	2,  // 11: vector.VectorService.UpsertEntries:output_type -> vector.UpsertEntriesResponse
	5,  // 12: vector.VectorService.Search:output_type -> vector.SearchResponse
	7,  // 13: vector.VectorService.DeleteByArtifact:output_type -> vector.DeleteByArtifactResponse
	9,  // 14: vector.VectorService.ListEntries:output_type -> vector.ListEntriesResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_vector_proto_init() }
func file_vector_proto_init() {
	if File_vector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vector_proto_rawDesc), len(file_vector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vector_proto_goTypes,
		DependencyIndexes: file_vector_proto_depIdxs,
		MessageInfos:      file_vector_proto_msgTypes,
	}.Build()
	File_vector_proto = out.File
	file_vector_proto_goTypes = nil
	file_vector_proto_depIdxs = nil
}
