// Package server contains generated proto types
// NOTE: This file provides stub types until proto generation is set up

package server

// Stub types for gRPC - will be replaced by protoc-generated code

type UnimplementedAgentServiceServer struct{}

type ChatRequest struct {
	Query           string
	ConversationId  string
	ContextEntities []string
	SessionId       *string
}

func (r *ChatRequest) GetSessionId() string {
	if r.SessionId != nil {
		return *r.SessionId
	}
	return ""
}

type ChatResponse struct {
	Response        string
	Reasoning       []*ReasoningStep
	Artifacts       []*Artifact
	Citations       []string
	ProposedActions []*ProposedAction
}

type ChatChunk struct {
	Content   string
	Done      bool
	Reasoning *ReasoningStep
}

type ReasoningStep struct {
	Step       int32
	Type       string
	Content    string
	DurationMs int64
}

type Artifact struct {
	Id       string
	Type     string
	Title    string
	Content  string
	Language *string
}

type ProposedAction struct {
	Id          string
	Type        string
	Title       string
	Description string
}

type ActionRequest struct {
	ActionType     string
	EntityId       string
	EntityType     string
	Source         string
	Payload        string
	ConversationId *string
}

type ActionResponse struct {
	Success       bool
	ActionType    string
	EntityId      string
	Message       string
	Timestamp     *string
	PreviousState *string
	NewState      *string
}

// Server interfaces - will be generated by protoc
type AgentService_StreamChatServer interface {
	Send(*ChatChunk) error
	Context() interface{ Done() <-chan struct{} }
}

func RegisterAgentServiceServer(s interface{}, srv *AgentServer) {}
